title: Robber Barons or Captains of Industry Project
description: >
  A project on industrial leaders for a US History class.
baseurl: "/RobberBaronsProject"
url: "https://zachdeibert.github.io"
markdown: kramdown
